//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KsIndexerNET {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KsIndexerNET.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KsIndexer V.
        /// </summary>
        internal static string ABOUT1 {
            get {
                return ResourceManager.GetString("ABOUT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indexador de documentos para Kindle Scribe.
        /// </summary>
        internal static string ABOUT2 {
            get {
                return ResourceManager.GetString("ABOUT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un anexo con ese nombre.
        /// </summary>
        internal static string ANNEX_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ANNEX_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anexos.
        /// </summary>
        internal static string ANNEXES {
            get {
                return ResourceManager.GetString("ANNEXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistentes.
        /// </summary>
        internal static string ATTENDANTS {
            get {
                return ResourceManager.GetString("ATTENDANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proceso de compactación de la base de datos puede tardar varios minutos.
        /// </summary>
        internal static string COMPACT_DATABASE {
            get {
                return ResourceManager.GetString("COMPACT_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        internal static string COMPANY {
            get {
                return ResourceManager.GetString("COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar el documento actual?.
        /// </summary>
        internal static string CONFIRM_DELETE_DOC {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los datos se perderán.
        /// </summary>
        internal static string CONFIRM_DELETE_DOC1 {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE_DOC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de salir de la Aplicación?.
        /// </summary>
        internal static string CONFIRM_EXIT_APP {
            get {
                return ResourceManager.GetString("CONFIRM_EXIT_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un PDF para este documento.
        /// </summary>
        internal static string CONFIRM_PDF_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("CONFIRM_PDF_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de actualizarlo?.
        /// </summary>
        internal static string CONFIRM_PDF_ALREADY_EXISTS1 {
            get {
                return ResourceManager.GetString("CONFIRM_PDF_ALREADY_EXISTS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error interno. No se pudo cargar el archivo.
        /// </summary>
        internal static string COULD_NOT_LOAD_FILE {
            get {
                return ResourceManager.GetString("COULD_NOT_LOAD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión de la base de datos: .
        /// </summary>
        internal static string DB_INFO1 {
            get {
                return ResourceManager.GetString("DB_INFO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño de la base de datos: .
        /// </summary>
        internal static string DB_INFO2 {
            get {
                return ResourceManager.GetString("DB_INFO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        internal static string DLG_CONFIRM {
            get {
                return ResourceManager.GetString("DLG_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string DLG_ERROR {
            get {
                return ResourceManager.GetString("DLG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string DLG_INFO {
            get {
                return ResourceManager.GetString("DLG_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso.
        /// </summary>
        internal static string DLG_WARN {
            get {
                return ResourceManager.GetString("DLG_WARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El documento actual ha cambiado.
        /// </summary>
        internal static string DOC_HAS_CHANGED {
            get {
                return ResourceManager.GetString("DOC_HAS CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe un documento con Id.
        /// </summary>
        internal static string DOC_ID_NOT_FOUND {
            get {
                return ResourceManager.GetString("DOC_ID_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento guardado con Id.
        /// </summary>
        internal static string DOC_SAVED_WITH_ID {
            get {
                return ResourceManager.GetString("DOC_SAVED_WITH_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa (opcional).
        /// </summary>
        internal static string ENTER_ATT_COMPANY {
            get {
                return ResourceManager.GetString("ENTER_ATT_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del asistente.
        /// </summary>
        internal static string ENTER_ATT_NAME {
            get {
                return ResourceManager.GetString("ENTER_ATT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca la fecha.
        /// </summary>
        internal static string ENTER_DATE {
            get {
                return ResourceManager.GetString("ENTER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entre el Id del documento a buscar.
        /// </summary>
        internal static string ENTER_ID_TO_SEARCH {
            get {
                return ResourceManager.GetString("ENTER_ID_TO_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca etiquetas separadas por blancos.
        /// </summary>
        internal static string ENTER_KEYWORDS {
            get {
                return ResourceManager.GetString("ENTER_KEYWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca nuevo valor.
        /// </summary>
        internal static string ENTER_NEW_VALUE {
            get {
                return ResourceManager.GetString("ENTER_NEW_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error accediendo a la base de datos.
        /// </summary>
        internal static string ERROR_ACCES_DATABASE {
            get {
                return ResourceManager.GetString("ERROR_ACCES_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra la base de datos. Reinstale la aplicación.
        /// </summary>
        internal static string ERROR_DB_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_DB_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha prodcido un error al eliminar el documento.
        /// </summary>
        internal static string ERROR_DELETE_DOC {
            get {
                return ResourceManager.GetString("ERROR_DELETE_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido cargar el archivo anexo.
        /// </summary>
        internal static string ERROR_LOADING_ANNEX {
            get {
                return ResourceManager.GetString("ERROR_LOADING_ANNEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error leyendo el archivo.
        /// </summary>
        internal static string ERROR_READ_FILE {
            get {
                return ResourceManager.GetString("ERROR_READ_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error al acceder al documento con Id.
        /// </summary>
        internal static string ERROR_RETRIEVING_DOC_WITH_ID {
            get {
                return ResourceManager.GetString("ERROR_RETRIEVING_DOC_WITH_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error guardando el documento.
        /// </summary>
        internal static string ERROR_SAVE_DOC {
            get {
                return ResourceManager.GetString("ERROR_SAVE_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error guardando el archivo temporal.
        /// </summary>
        internal static string ERROR_SAVE_TEMP_FILE {
            get {
                return ResourceManager.GetString("ERROR_SAVE_TEMP_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar la base de datos.
        /// </summary>
        internal static string ERROR_UPDATE_DB {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error creando el archivo temporal.
        /// </summary>
        internal static string ERROR_WRITE_TEMP {
            get {
                return ResourceManager.GetString("ERROR_WRITE_TEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de instalación. No se encuentra la tabla DbVersion o no tiene un contenido válido.
        /// </summary>
        internal static string ERROR_WRONG_DB {
            get {
                return ResourceManager.GetString("ERROR_WRONG_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elimine la BD anterior y reinstale.
        /// </summary>
        internal static string ERROR_WRONG_DB1 {
            get {
                return ResourceManager.GetString("ERROR_WRONG_DB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los archivos (*.*)|*.*.
        /// </summary>
        internal static string FILTER_ALL_FILES {
            get {
                return ResourceManager.GetString("FILTER_ALL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede cargar un directorio.
        /// </summary>
        internal static string FOLDER_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("FOLDER_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay nungún documento seleccionado.
        /// </summary>
        internal static string NO_DOC_SELECTED {
            get {
                return ResourceManager.GetString("NO_DOC_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se han encontrado documentos con esos criterios.
        /// </summary>
        internal static string NO_DOCUMENT_FOUND {
            get {
                return ResourceManager.GetString("NO_DOCUMENT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir al menos un criterio de búsqueda.
        /// </summary>
        internal static string NO_SEARCH_CRITERIA {
            get {
                return ResourceManager.GetString("NO_SEARCH_CRITERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay texto importado para procesar.
        /// </summary>
        internal static string NO_TEXT_TO_PROCESS {
            get {
                return ResourceManager.GetString("NO_TEXT_TO_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de continuar?.
        /// </summary>
        internal static string OK_TO_PROCEED {
            get {
                return ResourceManager.GetString("OK_TO_PROCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Continuar sin guardar?.
        /// </summary>
        internal static string PROCEED_WITHOUT_SAVE {
            get {
                return ResourceManager.GetString("PROCEED_WITHOUT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un documento con el mismo titulo y fecha/hora.
        /// </summary>
        internal static string SIMILAR_DOC_EXISTS {
            get {
                return ResourceManager.GetString("SIMILAR_DOC_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño.
        /// </summary>
        internal static string SIZE {
            get {
                return ResourceManager.GetString("SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir al menos un criterio de búsqueda.
        /// </summary>
        internal static string SOME_CRITERIA_REQUIRED {
            get {
                return ResourceManager.GetString("SOME_CRITERIA_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El documento debe tener al menos un titulo y una fecha/hora.
        /// </summary>
        internal static string TITLE_AND_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("TITLE_AND_DATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se va proceder a actualizar la base de datos a la versión.
        /// </summary>
        internal static string UPDATE_DATABASE {
            get {
                return ResourceManager.GetString("UPDATE_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pulse OK para continuar.
        /// </summary>
        internal static string UPDATE_DATABASE1 {
            get {
                return ResourceManager.GetString("UPDATE_DATABASE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tamaño del archivo excede el límite de.
        /// </summary>
        internal static string WRONG_ANNEX_SIZE {
            get {
                return ResourceManager.GetString("WRONG_ANNEX_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha/hora no tiene un formato válido.
        /// </summary>
        internal static string WRONG_DATE_FORMAT {
            get {
                return ResourceManager.GetString("WRONG_DATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Id debe ser un número entero mayor que cero.
        /// </summary>
        internal static string WRONG_ID_ENTERED {
            get {
                return ResourceManager.GetString("WRONG_ID_ENTERED", resourceCulture);
            }
        }
    }
}
